Generate Terraform config from volumeset templates
shakacode/control-plane-flow pull request #237
Opened 2024-10-17 15:29 UTC by zzaakiirr

### What does this PR do?

This PR adds support for converting templates with type: volumeset to terraform config format

### Terraform docs
https://registry.terraform.io/providers/controlplane-com/cpln/latest/docs/resources/volume_set

### Examples

```
kind: volumeset
name: postgres-poc-vs
description: postgres-poc-vs
spec:
  autoscaling:
    maxCapacity: 1000
    minFreePercentage: 1
    scalingFactor: 1.1
  fileSystemType: ext4
  initialCapacity: 10
  performanceClass: general-purpose-ssd
  snapshots:
    createFinalSnapshot: true
    retentionDuration: 7d
```

Transforms to:
```
resource "cpln_volume_set" "postgres-poc-vs" {
  gvc = cpln_gvc.app-name.name
  name = "postgres-poc-vs"
  description = "postgres-poc-vs"
  initial_capacity = 10
  performance_class = "general-purpose-ssd"
  file_system_type = "ext4"
  snapshots {
    create_final_snapshot = true
    retention_duration = "7d"
  }
  autoscaling {
    max_capacity = 1000
    min_free_percentage = 1
    scaling_factor = 1.1
  }
}
```

2024-10-21 12:48 UTC, zzaakiirr commented
@coderabbitai review

2024-10-21 13:31 UTC, zzaakiirr commented on spec/core/terraform_config/volume_set_spec.rb
> +              }
Current version is better because suggested version is not handling well indendations

2024-10-21 13:37 UTC, zzaakiirr commented
@coderabbitai review

2024-10-21 13:47 UTC, zzaakiirr commented on lib/core/terraform_config/volume_set.rb
> +      raise ArgumentError, "Invalid file system type: #{file_system_type}. Choose from #{FILE_SYSTEM_TYPES.join(', ')}"
Done

2024-10-22 13:01 UTC, rafaelgomesxyz requested changes

2024-10-22 14:16 UTC, zzaakiirr commented on spec/patches/string_spec.rb
> +      it "adds 's' to the end if it doesn't already end with 's'" do
Done

2024-10-22 14:16 UTC, zzaakiirr commented on lib/patches/string.rb
> +      end_with?("s") ? self : "#{self}s"
Simplified method and left comment for this method

2024-10-22 14:16 UTC, zzaakiirr commented on lib/core/terraform_config/generator.rb
> +    InvalidTemplateError = Class.new(ArgumentError)
Done

2024-10-22 14:20 UTC, rafaelgomesxyz approved these changes
LGTM

Waiting on review from @borela.

2024-10-22 14:30 UTC, borela approved these changes

2024-10-22 14:31 UTC, merged